### ISSUE TITLE
A version use 16-channel SPI

### ISSUE THREAD

**Issue by Fusenheizi** [KaetzelLab/Open-MAC#1]
Thank you very much for this project! It is well suited for my Intan RHD system. 

Additionally, I also use the **Intan RHS system** for animal stimulation, and the corresponding cable connector is the **Omnetics PZN-16 polarized nano**. Is there a version based on this available?

**Comment by KaetzelLab** [comment]
Thank you very much for your appreciation, Unfortunately, we do not have  PZN-16 polarized, I will upload the Altium design file sooner and maybe you can modify it with a PZN-16 polarized nano footprint.

**Comment by Fusenheizi** [comment]
> Thank you very much for your appreciation, Unfortunately, we do not have  PZN-16 polarized, I will upload the Altium design file sooner and maybe you can modify it with a PZN-16 polarized nano footprint.

Thank you for your response! I will make modifications based on the file you uploaded later.

**Comment by KaetzelLab** [comment]
https://github.com/KaetzelLab/Open-MAC/PCB Altium files files.zip

**Comment by KaetzelLab** [comment]
https://github.com/KaetzelLab/Open-MAC/PCB Altium files files.zip

**Comment by KaetzelLab** [comment]
https://github.com/KaetzelLab/Open-MAC/PCB Altium files files.zip

**Comment by KaetzelLab** [comment]
https://github.com/KaetzelLab/Open-MAC/PCB Altium files files.zip
